---
- name: Crear estructura de directorios en /vm
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /vm
    - /vm/iso
    - /vm/iso/debian-iso-work
  notify: Mostrar mensaje directorios

- name: Descargar ISO de Debian desde la página oficial
  get_url:
    url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.1.0-amd64-netinst.iso
    dest: /vm/iso/debian-13.1.0-amd64-netinst.iso
    mode: '0644'
  notify: Mostrar mensaje copia iso

- name: Generar hash sha-512 de la contraseña
  command: mkpasswd -m sha-512 '1234'
  register: hashed_pass

- name: Guardar hash en un archivo para uso posterior
  copy:
    dest: /vm/iso/hashed_password.txt
    content: "{{ hashed_pass.stdout }}"
    mode: '0600'
  notify: Mostrar mensaje hash
