---
- name: Remove old Docker keyring (.asc) if exists
  file:
    path: /etc/apt/keyrings/docker.asc
    state: absent

- name: Remove old Docker repository file if exists
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Remove any docker repo fragments
  shell: rm -f /etc/apt/sources.list.d/docker*.list

- name: Ensure required packages are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
  notify: Update apt cache
