---
- name: Set hostname persistently
  block:
    - name: Set system hostname
      ansible.builtin.command:
        cmd: "hostnamectl set-hostname {{ hostname }}"
      become: true

    - name: Ensure hostname is in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\\.0\\.1\\.1\\s+'
        line: "127.0.1.1   {{ hostname }}"
        state: present
      become: true

    # - name: Ensure both VMs are resolvable locally
    #   ansible.builtin.lineinfile:
    #     path: /etc/hosts
    #     line: "{{ item }}"
    #     state: present
    #   loop:
    #     - "192.168.1.9   k8s-master"
    #     - "192.168.56.12 k8s-worker"
    #   become: true

    - name: Restart hostname service (for graphical sessions)
      ansible.builtin.systemd:
        name: systemd-hostnamed
        state: restarted
      become: true

    - name: Verify new hostname
      ansible.builtin.command: hostnamectl
      register: hostnamectl_output
      changed_when: false
      become: true

    - name: Show confirmation
      ansible.builtin.debug:
        msg: |
          ✅ Hostname configurado correctamente:
          {{ hostnamectl_output.stdout }}
  when: hostname is defined
